### ISSUE TITLE
Suggestions on sync-by-frame communication between Unity and ZeroMQ?

### ISSUE THREAD

**Issue by hukaidong** [valkjsaaa/Unity-ZeroMQ-Example#10]
I'm currently working on a project which have a sync-by-frame behavior between server (Unity) and Client(python). The intuitive implementation with non-threading zmq leads unity editor to freeze after every time stop playing. I've tried put NetMQConfig.cleanup on several places (onDestory/onApplicationQuit) but non of those works. For the solution of two threads with mutex is a little bit wierd (since the model apprently works on a single thread behavior, is it?) and is my last will to accomplish. Is there any suggestion on how to deal with it? Thanks very much!

---
The basic pattern would be: unity runs one frame, send data to python, python send back intructions for the next step, and unity executes intructions on the next frame.

**Comment by valkjsaaa** [comment]
My recommendation is some how initialize a thread dedicated to initialize and clean up NetMQ stuff, and only use the channel you created in the other thread on the main thread for communication and upon closing, cleanup the NetMQ objects on the second thread.

**Comment by hukaidong** [comment]
Thanks a lot.
