### ISSUE TITLE
How do you get the latest stable NetMq release binary?

### ISSUE THREAD

**Issue by offchan42** [valkjsaaa/Unity-ZeroMQ-Example#7]
As the title said, how do you get `.dll` files that are required for using `NetMQ`?

I read the document of NetMq and it said that I have to install via NuGet. But I tried installing a package there before and Unity didn't recognize it.

**Comment by offchan42** [comment]
In other words, how do you install `NetMQ` in Unity easily?

**Comment by valkjsaaa** [comment]
I do it by:

- Create a empty C# project in Visual Studio or Rider
- Open Package Manager in IDE and install NetMQ
- Go to `Packages/` and copy the .NET 4 variant of the DLL file.

I recommend you just download the DLL file in this repository.

**Comment by valkjsaaa** [comment]
It's all [here](https://github.com/valkjsaaa/Unity-ZeroMQ-Example/blob/62cea161dce110af5ef95f235dd552aab8808129/Assets/)

You will also need the `AsyncIO.dll` for NetMQ to work.

**Comment by offchan42** [comment]
Thank you!
